---

- name: Configuration for Stepup-VM
  hosts: all
  become: True
  gather_facts: True
  serial: 1

  tasks:
      - name: Set yum cache dir to /vagrant/yum/... dir (that is mounted on the host)
        lineinfile: dest=/etc/yum.conf regexp=^cachedir= line=cachedir=/vagrant/yum/$basearch/$releasever

      - name: Set keepcache=1
        lineinfile: dest=/etc/yum.conf regexp=^keepcache= line=keepcache=1

      - name: Exclude kernel packages in yum
        lineinfile: dest=/etc/yum.conf regexp=^exclude=kernel line=exclude=kernel*

      # Manage networking the old fashioned way
      - name: Stop & Disable NetworkManager service
        service: name=NetworkManager state=stopped enabled=false

      - name: Create a config for ens32 in /etc/sysconfig/network-scripts/ifcfg-ens32
              # ... that replaces the ifcfg-ens33 one that was overwritten by vagrant
              # ens32 now survives vagrant reload / up / halt
        copy:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens32
            content: |
                NAME="ens32"
                DEVICE="ens32"
                ONBOOT=yes
                NETBOOT=yes
                IPV6INIT=yes
                BOOTPROTO=dhcp
                TYPE=Ethernet
                DEFROUTE=yes
                IPV4_FAILURE_FATAL=no
                IPV6_AUTOCONF=yes
                IPV6_DEFROUTE=yes
                IPV6_FAILURE_FATAL=no
                PEERDNS=yes
                PEERROUTES=yes
                IPV6_PEERDNS=yes
                IPV6_PEERROUTES=yes
                NM_MANAGED=no
        when: ansible_virtualization_type == "VMware"

      # Always restart the network
      # If something is wrong with the networking config of the VM, this is likely to show up here
      - name: Restart networking
        service: name=network state=restarted

