---

- name: Configuration for Stepup-VM
  hosts: all
  become: True
  gather_facts: False
  serial: 1

  tasks:
      - name: Set yum cache dir to /vagrant/yum/... dir (that is mounted on the host)
        lineinfile: dest=/etc/yum.conf regexp=^cachedir= line=cachedir=/vagrant/yum/$basearch/$releasever

      - name: Set keepcache=1
        lineinfile: dest=/etc/yum.conf regexp=^keepcache= line=keepcache=1

      - name: Exclude kernel packages in yum
        lineinfile: dest=/etc/yum.conf regexp=^exclude=kernel line=exclude=kernel*

      # Vagrant modified network, but did not restart it so the 2nd NIC with fixed IP does not show up
      # If something is wrong with the networking config of the VM, this is likely to show up here
      - name: Restart networking
        service: name=network state=restarted
