---

- name: Configuration for Stepup-VM
  hosts: all
  become: True
  gather_facts: False
  serial: 1

  tasks:
      - name: Set yum cache dir to /vagrant/yum/... dir (that is mounted on the host)
        lineinfile: dest=/etc/yum.conf regexp=^cachedir= line=cachedir=/vagrant/yum/$basearch/$releasever

      - name: Set keepcache=1
        lineinfile: dest=/etc/yum.conf regexp=^keepcache= line=keepcache=1

      - name: Exclude kernel packages in yum
        lineinfile: dest=/etc/yum.conf regexp=^exclude=kernel line=exclude=kernel*

      - name: Create ens32 config in /etc/sysconfig/network-scripts/ifcfg-ens32
        copy:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens32
            content: |
                DEVICE="ens32"
                BOOTPROTO="static"
                IPADDR="{{host_ipv4}}"
                NETMASK="255.255.255.0"
                NM_CONTROLLED="no"
                ONBOOT="yes"
                TYPE="Ethernet"
                DEFROUTE="no"
                PEERDNS="no"
                PEERROUTES="no"
                IPV4_FAILURE_FATAL="yes"
                IPV6INIT="no"
                IPV6_AUTOCONF="no"
                IPV6_DEFROUTE="no"
                IPV6_PEERDNS="no"
                IPV6_PEERROUTES="no"
                IPV6_FAILURE_FATAL="no"
                NAME="ens32"
        notify: Restart networking

  handlers:
      - name: Restart networking
        action: service name=network state=restarted