---

- name: Configuration for Stepup-VM
  hosts: all
  become: True
  gather_facts: False
  serial: 1

  tasks:
      - name: Set yum cache dir to /vagrant/yum/... dir (that is mounted on the host)
        lineinfile: dest=/etc/yum.conf regexp=^cachedir= line=cachedir=/vagrant/yum/$basearch/$releasever

      - name: Set keepcache=1
        lineinfile: dest=/etc/yum.conf regexp=^keepcache= line=keepcache=1

      - name: Exclude kernel packages in yum
        lineinfile: dest=/etc/yum.conf regexp=^exclude=kernel line=exclude=kernel*
