# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "puppetlabs/centos-7.2-64-nocm"
  #config.vm.box = "centos/7"
  
  # Stepup-Deploy Ansible playbook takes the hostname from the inventory which is generated by Vagrant
  # We define the vm here with it's full hostname because that is what is put in the generated inventory
  # Tip: After spinning up de VM(s) with vagrant you can use bash 4 commandline completion for completing hostname in Vagrant
  #      With ansible-playbook you can use e.g. "-l app*" to safe typing
  config.vm.define "app.stepup.example.com" do |app|

    app.vm.synced_folder "./src/", "/src", :mount_options => ["dmode=777","fmode=666"]

    # Let vagrant create a 192.168.66.0/24 network and add a second nic to the VM for it
    # The VM will have two NICs:
    # - The default NIC with a DHCP address, this is the NIC that will be used when "vagrant ssh app.stepup.example.com"
    # -
    app.vm.network :private_network, ip: "192.168.66.3"
    app.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"] = "1536"
      v.vmx["numvcpus"] = "1"
      #v.gui = true
    end
    app.vm.provider "virtualbox" do |v|
      # Use the default (vboxsf)
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  config.vm.define "manage.stepup.example.com" do |manage|
    #app.vm.synced_folder ".", "/vagrant", disabled: true

    # Let vagrant create a 192.168.66.0/24 network and add a second nic to the VM for it
    manage.vm.network :private_network, ip: "192.168.66.4"
    manage.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"] = "1536"
      v.vmx["numvcpus"] = "1"
      #v.gui = true
    end
    manage.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  # Let Vagrant generate an "inventory" file for Ansible
  # This inventory file can be used by the Ansible playbooks in Stepup-Deploy
  # To let Vagrant regenerate the inventory file run:
  #     vagrant provision
  config.vm.provision "ansible" do |ansible|

    # Use Ansible to make a few additional changes to the VM. This is not the main deploy of Stepup. This playbook:
    # - Configures YUM to use a RPM package cache in the current directory
    # - Excludes kernel packages from updates
    # - Restarts networking
    ansible.playbook = "provision.yml"

    ansible.groups = {
      "app" => ["app.stepup.example.com"],
      "stepup-app" => ["app.stepup.example.com"],
      "dbcluster:children" => ["stepup-app"],
      "manage" => ["manage.stepup.example.com"],
      "es:children" => ["manage"],
      "proxy:children" => ["stepup-app"],
      "stepup-gateway:children" => ["stepup-app"],
      "stepup-selfservice:children" => ["stepup-app"],
      "stepup-ra:children" => ["stepup-app"],
      "stepup-middleware:children" => ["stepup-app"],
      "stepup-tiqr:children" => ["stepup-app"],
      "stepup-keyserver:children" => ["stepup-app"],
      # Don't use a sparate lb, use the proxy role instead.
      # It set's up a simple reverse proxy using nginx op the app server
      "lb" => [],
      "ks" => [],
      "ks:children" => ["app"]
    }

    ansible.host_vars = {
          "app.stepup.example.com" => {"host_ipv4" => "192.168.66.3", "backend_ipv4" => "192.168.66.3"},
          "manage.stepup.example.com" => {"host_ipv4" => "192.168.66.4"}
        }
    #ansible.verbose = "vvvv"
  end

end
